name: transformers
channels:
  - defaults
  - conda-forge
  - fastai
  - apple
dependencies:
  - python=3.9
  - pip
  - jupyter
  - ipykernel
  - pip:
    - graphviz  
    - seaborn
    - matplotlib
    - bokeh
    - numpy
    - pandas
    - nbdev
    - torch
    - mypy









    

