# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/utils.ipynb.

# %% auto 0
__all__ = ['save_model', 'load_model']

# %% ../notebooks/utils.ipynb 1
import os
from pathlib import Path
import torch


def save_model(model, model_name, model_version, iter):
    model_path = Path("../models") / f"{model_name}-{model_version}-{iter}.pt"
    os.makedirs("../models/", exist_ok=True)
    torch.save(model, model_path)


def load_model(model_name, model_version, iter, weights_only=False):
    model_path = Path(f"../models") / f"{model_name}-{model_version}-{iter}.pt"
    return torch.load(model_path, weights_only=False)
